#
# GNUmakefile - Generated by ProjectCenter
#

include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.2
PACKAGE_NAME = ViewPDF
APP_NAME = ViewPDF
ViewPDF_APPLICATION_ICON = 
ViewPDF_MAIN_MODEL_FILE = Main

#
# Used Libraries
#
ViewPDF_LIB_DIRS =
ViewPDF_GUI_LIBS = -lPopplerKit

#
# Global Resource files
#
ViewPDF_RESOURCE_FILES = \
Images/First.png \
Images/Last.png \
Images/Next.png \
Images/Previous.png \
Images/ZoomIn.png \
Images/ZoomOut.png \
Images/Fit*.png

#
# Language Resources
#
ViewPDF_LANGUAGES = English 
ViewPDF_LOCALIZED_RESOURCE_FILES = \
Main.gorm \
Document.gorm

#
# Class files
#
ViewPDF_OBJC_FILES = \
AppDelegate.m \
CenteringClipView.m \
Controller.m \
Document.m \
DocumentTools.m \
DocumentWindow.m \
ExtendedScrollView.m \
main.m \
MenuState.m \
NSView+Scrolling.m \
PDFContentView.m \
Preferences.m \
SinglePageView.m \
ToolViewBuilder.m \
ZoomFactor.m

#
# C files
#
ViewPDF_C_FILES = 

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
